// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixvqiommawrcktvdiwpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4dnFpb21tYXdyY2t0dmRpd3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NjE5MTksImV4cCI6MjA1MjIzNzkxOX0.E3QP4ItJyYnFr00HfOdFdjamyPHmgk5asstq0iP_VCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);